version: '3.9'

services:
  web_1:
    build: web/.
    depends_on:
      - db
    links:
      - db
    environment:
      DATABASE_URL: postgresql://myuser:abc@db/mydb
      NAME: web_1
      RABBITMQ_URL: amqp://myuser:abc@rabbit:5672/%2F
  web_2:
    build: web/.
    depends_on:
      - db
    links:
      - db
    environment:
      DATABASE_URL: postgresql://myuser:abc@db/mydb
      NAME: web_2
      RABBITMQ_URL: amqp://myuser:abc@rabbit:5672/%2F
  loader:
    build: loader/.
    restart: on-failure
    depends_on:
      - rabbit
      - nginx
    links:
      - rabbit
      - nginx
    environment:
      RABBITMQ_URL: amqp://myuser:abc@rabbit:5672/%2F
      WEB_BASE_URL: http://nginx:80
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: abc
    volumes:
      - "dbdata://var/lib/postgresql/data"
  rabbit:
    image: rabbitmq:management
    hostname: rabbit
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: abc
    healthcheck:
      test: ["CMD", "CURL", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
  nginx:
    build: nginx/.
    ports:
      - "8080:80"
    depends_on:
      - web_1
      - web_2
    links:
      - web_1
      - web_2
volumes:
  dbdata: