version: '3.9'

services:
  web:
    build: web/.
    ports:
      - "8080:8000"
    depends_on:
      - db
    links:
      - db
    environment:
      DATABASE_URL: postgresql://myuser:abc@db/mydb
  loader:
    build: loader/.
    restart: on-failure
    depends_on:
      - rabbit
      - web
    links:
      - rabbit
      - web
    environment:
      RABBITMQ_URL: amqp://myuser:abc@rabbit:5672/%2F
      WEB_BASE_URL: http://web:8000
  db:
    image: postgres
    restart: always
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: abc
    volumes:
      - "dbdata://var/lib/postgresql/data"
  rabbit:
    image: rabbitmq:management
    hostname: rabbit
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: abc
    healthcheck:
      test: ["CMD", "CURL", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
volumes:
  dbdata: